D='https://YOUR-DOMAIN.vercel.app'
N=[('index','Home'),('about','About Us'),('services','Services'),('products','AI Products'),('pricing','Pricing'),('contact','Contact Us')]
T={'index':'NextGenAI | AI Products, Business Automation & Creative AI','about':'About NextGenAI | Our Mission and AI Product Vision','services':'AI Development & Automation Services | NextGenAI','products':'Explore AI Products | Contractor AI, Business Manager & Cineforge','pricing':'AI Product Pricing & Business Solutions | NextGenAI','contact':'Contact NextGenAI | AI Product & Partnership Inquiries','privacy':'Privacy Policy | NextGenAI','terms':'Terms of Service | NextGenAI','404':'Page not found | NextGenAI'}
LOGO='<svg width="34" height="34" viewBox="0 0 40 40" fill="none" stroke="#00E5FF" stroke-width="2" aria-hidden="true"><path d="M20 6c-6 0-10 4-10 9 0 2 .6 3.600 1.600 5-1 1.200-1.600 2.800-1.600 4.500 0 4 3.500 6.500 7 6.500h6c3.500 0 7-2.500 7-6.500 0-1.700-.6-3.300-1.600-4.500 1-1.400 1.600-3 1.600-5 0-5-4-9-10-9z"/><circle cx="16" cy="16" r="2" fill="#743BFF"/><circle cx="24" cy="18" r="2" fill="#00BFFF"/><path d="M16 16l8 2M20 22v6"/></svg>'
P=[('Contractor AI','AI Lead Management','Designed for roofing contractors who want to improve lead response, automate customer follow-ups, and simplify inspection appointment management.',['Lead follow-up workflows','AI-assisted SMS communication','Prospect qualification','Inspection scheduling','Appointment management'],'https://contractorai-nine.vercel.app/'),
('AI Business Manager','AI Business Operations','Brings AI-assisted marketing and business content workflows together to help companies manage repetitive digital marketing tasks more efficiently.',['AI-generated marketing content','Social media content preparation','SEO and blog writing assistance','Email content generation','Brand-oriented post composition','Social publishing integrations'],'https://ai-business-manager-alpha.vercel.app/login'),
('Cineforge AI','AI Video Creation','Helps users explore cinematic video creation through text-driven creative workflows, designed for promotional content, storytelling, and social media.',['Prompt-based video creation','Cinematic content workflows','Creative concept development','Voice generation, where supported','Social media video concepts'],'https://cineforge-ai-zeta.vercel.app/')]
def pcard(p,full=True):
    li=''.join(f'<li>{x}</li>' for x in p[3]) if full else ''
    return f'<div class="card"><span class="tag">{p[1]}</span><h3>{p[0]}</h3><p>{p[2]}</p>'+(f'<ul>{li}</ul><p class="note">Capabilities are subject to actual implementation in the live product.</p>' if full else '')+f'<a class="btn p" href="{p[4]}" target="_blank" rel="noopener">{"Visit" if full else "Explore"} {p[0]}</a></div>'
def cards(items): return '<div class="grid">'+''.join(f'<div class="card"><h3>{a}</h3><p>{b}</p></div>' for a,b in items)+'</div>'
def form(t,extra,btn):
    return f'<form class="card" data-type="{t}" novalidate><label>Full Name<input name="Name" required autocomplete="name"></label><label>Email<input name="Email" type="email" required autocomplete="email"></label>{extra}<label>Message<textarea name="Message" rows="4" required></textarea></label><input class="hp" name="website" tabindex="-1" autocomplete="off" aria-hidden="true"><label class="chk"><input type="checkbox" required> I agree that my details may be used to reply to this message (see the <a href="/privacy" class="g">Privacy Policy</a>).</label><button class="btn p" type="submit">{btn}</button><div class="st" role="status" aria-live="polite"></div></form>'
def inp(n,r=''): return f'<label>{n}<input name="{n}" {r}></label>'
def page(slug,body):
    nav=''.join(f'<a href="/{"" if s=="index" else s}"{" class=on aria-current=page" if s==slug else ""}>{n}</a>' for s,n in N)
    return f'''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{T[slug]}</title>
<meta name="description" content="NextGenAI builds practical AI applications for lead management, business automation and AI video creation."><meta property="og:title" content="{T[slug]}"><meta property="og:type" content="website"><meta property="og:url" content="{D}/{'' if slug=='index' else slug}">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 10 10%27%3E%3Ctext y=%279%27 font-size=%279%27%3E%F0%9F%A7%A0%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;600;800&display=swap"><link rel="stylesheet" href="/style.css"></head><body>
<canvas id="bg" aria-hidden="true"></canvas><header><nav aria-label="Main"><div class="w"><a class="logo" href="/" aria-label="NextGenAI home">{LOGO}<span>NextGenAI<small>Build. Automate. Innovate.</small></span></a><button id="mb" aria-expanded="false" aria-controls="lk">Menu</button><div class="links" id="lk">{nav}<a href="https://ai-business-manager-alpha.vercel.app/login" target="_blank" rel="noopener">Login</a></div><a class="btn p" href="/products">Explore Products</a></div></nav></header>
<main>{body}</main><footer><div class="w"><div class="grid"><div><h4>NextGenAI</h4><p>Build. Automate. Innovate.<br>Practical AI applications for a smarter digital future.</p></div><div><h4>Company</h4><a href="/about">About Us</a><a href="/services">Our Services</a><a href="/about#vision">Our Vision</a><a href="/contact#invest">Investor Relations</a><a href="/contact">Contact Us</a></div><div><h4>AI Products</h4>'''+''.join(f'<a href="{p[4]}" target="_blank" rel="noopener">{p[0]}</a>' for p in P)+f'''</div><div><h4>Contact</h4><a href="mailto:shahiqealikazmi@gmail.com">shahiqealikazmi@gmail.com</a><a href="tel:+923129595075">+92 312 9595075</a></div></div>
<p style="margin-top:28px"><a href="/privacy" style="display:inline">Privacy Policy</a> &nbsp; <a href="/terms" style="display:inline">Terms of Service</a> &nbsp; © <span id="yr"></span> NextGenAI. All rights reserved.</p></div></footer><script src="/app.js"></script></body></html>'''
def head(h,l,sub=''): return f'<section><div class="w"><h1>{h}</h1><p class="lead">{l}</p>{sub}</div></section>'
caps=[('Artificial Intelligence','<circle cx="17" cy="17" r="6"/><path d="M17 3v8M17 23v8M3 17h8M23 17h8"/>'),('Machine Learning','<circle cx="6" cy="9" r="3"/><circle cx="6" cy="25" r="3"/><circle cx="17" cy="17" r="3"/><circle cx="28" cy="17" r="3"/><path d="M9 9l5 7M9 25l5-7M20 17h5"/>'),('Data Science','<path d="M4 29V5M4 29h26"/><rect x="9" y="17" width="4" height="9"/><rect x="17" y="10" width="4" height="16"/><rect x="25" y="14" width="4" height="12"/>'),('Predictive Analytics','<path d="M4 26l8-9 6 5 12-15M24 7h6v6"/>'),('Intelligent Automation','<circle cx="17" cy="17" r="5"/><path d="M17 3v5M17 26v5M3 17h5M26 17h5"/>'),('AI-Powered Content Creation','<rect x="4" y="8" width="26" height="18" rx="3"/><path d="M14 13l7 4-7 4z"/>')]
capH='<div class="grid">'+''.join(f'<div class="card" style="display:flex;gap:12px;align-items:center;font-weight:600"><svg width="34" height="34" viewBox="0 0 34 34" fill="none" stroke="#00E5FF" stroke-width="2" aria-hidden="true">{d}</svg>{n}</div>' for n,d in caps)+'</div>'
bot=lambda x,y,c:f'<g class="bot"><rect x="{x}" y="{y}" width="42" height="34" rx="9" fill="#071426" stroke="{c}"/><circle cx="{x+13}" cy="{y+16}" r="4" fill="{c}"/><circle cx="{x+29}" cy="{y+16}" r="4" fill="{c}"/></g>'
core=f'<div class="core" aria-hidden="true"><svg viewBox="0 0 400 400"><defs><radialGradient id="rg"><stop offset="0" stop-color="#00E5FF" stop-opacity=".8"/><stop offset=".5" stop-color="#743BFF" stop-opacity=".3"/><stop offset="1" stop-opacity="0"/></radialGradient></defs><circle cx="200" cy="200" r="190" fill="url(#rg)" opacity=".5"/><circle class="ring" cx="200" cy="200" r="170" stroke="#00BFFF" stroke-dasharray="6 10"/><ellipse class="ring r2" cx="200" cy="200" rx="150" ry="55" stroke="#743BFF" stroke-width="2"/><circle cx="200" cy="200" r="62" fill="#071426" stroke="#00E5FF" stroke-width="2"/><path d="M170 200h60M200 170v60M178 178l44 44M222 178l-44 44" stroke="#00BFFF" opacity=".7"/><circle cx="200" cy="200" r="9" fill="#00E5FF"/>{bot(40,70,"#00E5FF")}{bot(310,290,"#743BFF")}{bot(305,60,"#00BFFF")}</svg></div>'
pages={}
pages['index']=f'''<section><div class="w hero"><div><h1>Build Your <span class="g">AI-Powered</span> Future</h1><p class="lead" style="color:var(--tx);font-weight:600">One Intelligent Platform. Limitless Possibilities.</p><p class="lead">Discover a smarter way to work with AI-powered business automation, intelligent lead management, and cinematic content creation. NextGenAI brings innovative AI applications together to help businesses work smarter, create faster, and grow globally.</p><div class="cta"><a class="btn p" href="/products">Explore Our AI Products</a><a class="btn" href="/contact#invest">Partner With Us</a></div></div>{core}</div></section>
<section><div class="w">{capH}</div></section>
<section><div class="w">{cards([("AI Products","A growing portfolio of specialized AI applications."),("Business Automation","Intelligent tools designed to simplify workflows."),("Creative AI","Tools for generating cinematic and marketing content."),("Global Vision","Building accessible AI solutions for businesses worldwide.")])}</div></section>
<section><div class="w"><h2>Featured Products</h2><div class="grid">{''.join(pcard(p,False) for p in P)}</div></div></section>
<section><div class="w two"><h2>Making Artificial Intelligence Useful for Everyone</h2><div><p>Our vision is to create an ecosystem of practical AI applications that help businesses solve real problems, reduce repetitive work, improve productivity, and unlock new creative possibilities. By bringing specialized AI tools together under one brand, we aim to make advanced technology more accessible to businesses of different sizes.</p><a class="btn" href="/about">Discover Our Mission</a></div></div></section>'''
pages['about']=head('Building the Next Generation of AI-Powered Solutions','NextGenAI is an emerging AI technology initiative focused on developing practical software products for business automation, intelligent lead management, and AI-powered content creation. Our approach combines modern web technologies, AI capabilities, and user-focused product design. Rather than building a single-purpose platform, our long-term vision is a growing ecosystem of specialized AI applications under one brand.')+'''<section id="vision"><div class="w two"><div class="card"><h2>Meet the Founder</h2><div class="pic">Photo placeholder</div><h3>Syed Shahiqe Ali Kazmi</h3><p style="color:var(--cyan)">Founder &amp; AI Product Developer</p><p>A web development and digital marketing professional with extensive experience in website development, business technology, digital marketing, and AI-powered product development.</p><p>His work combines modern web technologies, API integrations, AI-assisted development workflows, and practical business problem-solving. He is developing AI products that aim to simplify business operations, automate repetitive tasks, and help companies use artificial intelligence more effectively.</p><p>His current portfolio includes Contractor AI, AI Business Manager, and Cineforge AI.</p></div><div><h2>Our Mission</h2><p>To develop useful, accessible, and scalable AI products that empower businesses to automate workflows, improve efficiency, and create more value.</p><h3>Core Values</h3><ul><li><b>Innovation:</b> explore practical applications of emerging AI technologies.</li><li><b>Transparency:</b> communicate product capabilities and limitations honestly.</li><li><b>Accessibility:</b> make technology easier to use.</li><li><b>Reliability:</b> prioritize usability, security, and responsible development.</li><li><b>Continuous Improvement:</b> improve products through testing and customer feedback.</li></ul></div></div></section>'''
pages['services']=head('Intelligent AI Services for Modern Businesses','We develop and integrate AI-powered solutions that help businesses streamline operations, improve digital workflows, and explore new opportunities for growth.')+'<section><div class="w">'+cards([('AI Business Automation','Design intelligent workflows that reduce repetitive tasks and help teams operate more efficiently.'),('AI Agent and Assistant Development','Develop specialized AI assistants and agent-based workflows for defined business tasks, using appropriate models, integrations, and automation tools.'),('AI SaaS Product Development','Build modern web-based AI applications with responsive interfaces, API integrations, authentication, and scalable architecture.'),('AI-Powered Digital Marketing','Support content creation, social media planning, SEO workflows, marketing communication, and campaign preparation with AI-assisted tools.'),('AI Video and Content Creation','Explore AI-powered creative workflows for promotional videos, cinematic content, social media assets, and branded storytelling.'),('AI Integration and API Development','Connect suitable AI services, business applications, and APIs to create practical workflows tailored to business requirements.')])+'<p class="note" style="margin:22px 0">Custom development and consulting availability is confirmed per project. Not every service is a production-ready commercial offering.</p><a class="btn p" href="/contact">Discuss Your Project</a></div></section>'
pages['products']=head('Explore Our AI Product Ecosystem','Discover specialized AI applications designed to solve different business and creative challenges.')+f'<section><div class="w"><div class="grid">{"".join(pcard(p) for p in P)}</div><h2 style="margin-top:50px">In Development</h2><p>Future concepts only. These are not released products.</p><div class="grid">'+''.join(f'<div class="card dev"><span class="tag">Concept</span><h3>{x}</h3></div>' for x in ['AI Data Analytics','AI Customer Support','AI Workflow Automation','AI Research Assistant'])+'</div></div></section>'
pr=lambda t,d,l,c,h:f'<div class="card"><h3>{t}</h3><p>{d}</p><ul>'+''.join(f'<li>{x}</li>' for x in l)+f'</ul><a class="btn" href="{h}">{c}</a></div>'
pages['pricing']=head('Simple, Transparent Pricing','Choose the solution that fits your business. Explore our products and contact us for current pricing and availability.')+'<section><div class="w"><div class="grid">'+pr('Individual AI Products','Access an individual application according to its available plans.',['Product-specific capabilities','Separate application access where required','Product-specific support arrangements','Pricing confirmed on the relevant product website'],'Explore Products','/products')+pr('Business Solutions','Discuss AI solutions that match your business requirements.',['Identify relevant workflows','Discuss integration requirements','Define a suitable project scope','Obtain a tailored proposal'],'Request a Consultation','/contact')+pr('Enterprise and Custom AI','Explore tailored AI development and integration opportunities.',['Custom requirements discussion','AI workflow planning','API integration scoping','Project-specific proposals'],'Contact Us','/contact')+'</div><p class="note" style="margin-top:22px">Product pricing, subscription availability, usage limits, and third-party service charges may vary by application. Please confirm the applicable terms before purchasing.</p></div></section>'
pages['contact']=head("Let's Build Something Intelligent Together",'Have a question about our AI products, want to discuss a custom solution, or interested in exploring an investment or partnership opportunity? We would be happy to hear from you.')+'<section><div class="w two"><div><p>Email: <a class="g" href="mailto:shahiqealikazmi@gmail.com">shahiqealikazmi@gmail.com</a></p><p>Phone: <a class="g" href="tel:+923129595075">+92 312 9595075</a></p><p class="note">Privacy notice: details you submit are used only to reply to your message. See our <a class="g" href="/privacy">Privacy Policy</a>.</p></div>'+form('Contact message',inp('Company Name (optional)')+inp('Subject','required'),'Send Message')+'</div></section><section id="invest"><div class="w"><h2>Join Us in Building the Future of AI</h2><p class="lead">We are developing a portfolio of AI-powered applications and seeking strategic opportunities to grow the ecosystem. NextGenAI is open to conversations with investors, strategic partners, and technology professionals. We welcome discussions about product development, market opportunities, collaboration, and potential investment.</p><div class="two"><div class="grid" style="grid-template-columns:1fr"><div class="card"><h3>Strategic Investment</h3></div><div class="card"><h3>Technology Partnerships</h3></div><div class="card"><h3>Business Collaboration</h3></div></div>'+form('Investor inquiry',inp('Organization')+'<label>Inquiry Type<select name="Inquiry Type"><option>Strategic Investment</option><option>Technology Partnership</option><option>Business Collaboration</option></select></label>'+inp('Investment or Partnership Interest'),'Send Inquiry')+'</div></div></section>'
pages['privacy']=head('Privacy Policy','Last updated: replace with your publication date.')+'<section><div class="w doc"><h3>What we collect</h3><p>When you use our contact or investor forms we collect the name, email address, optional company or organization, and message you submit.</p><h3>How we use it</h3><p>We use these details only to reply to your inquiry. We do not sell your data.</p><h3>Service providers</h3><p>Form submissions are delivered by email through a third-party mail service. Our products are separate applications with their own privacy terms.</p><h3>Your choices</h3><p>To access or delete your details, email shahiqealikazmi@gmail.com.</p><p class="note">Draft template. Have it reviewed against the laws that apply to you before relying on it.</p></div></section>'
pages['terms']=head('Terms of Service','Last updated: replace with your publication date.')+'<section><div class="w doc"><h3>Use of this website</h3><p>This website provides information about NextGenAI and its products. Content is informational and not a binding offer.</p><h3>Products and third-party services</h3><p>Each AI application is a separate service with its own terms, pricing and usage limits. Please confirm those terms before purchasing. Third-party charges may apply.</p><h3>No guarantees</h3><p>Features described may be in development. We make no guarantee of specific results from AI-generated output.</p><h3>Contact</h3><p>Questions: shahiqealikazmi@gmail.com.</p><p class="note">Draft template. Have it reviewed by a qualified lawyer before relying on it.</p></div></section>'
pages['404']=head('Page not found','The page you are looking for does not exist.','<a class="btn p" href="/">Back to Home</a>')
for s,b in pages.items(): open(f'{s}.html','w').write(page(s,b))
open('sitemap.xml','w').write('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{D}/{"" if s=="index" else s}</loc></url>' for s in pages if s!='404')+'</urlset>')
open('robots.txt','w').write(f'User-agent: *\nAllow: /\nSitemap: {D}/sitemap.xml\n')
open('vercel.json','w').write('{"cleanUrls":true}')
